// ui/src/components/CodeAnalysisMetricHistory.vue
<template>
  <DynamicQuery
    title="Code quality metric history"
    subtitle="Retrieve historical metric data for workloads and repositories."
    :query-types="[QueryName.CodeCoverage]"
    @input="onInput"
  >
    <template v-slot:buttons>
      <v-btn @click="getHistoryAsCsv" color="secondary" class="ml-2">
        Download as CSV
      </v-btn>
    </template>
  </DynamicQuery>
</template>

<script lang="ts">
import DynamicQuery from "@/components/DynamicQuery.vue";
import { addAuthQueryParam } from "@/utils/axios";
import { CODE_ANALYSIS_METRIC_HISTORY_CSV, getApiBaseUrl } from "@/utils/urls";
import { logger } from "@/utils/logger";
import { QueryName } from "@/queries/queries";

type Inputs = {
  workloads: string[];
  repoGroups: string[];
  startDate: string;
};

export default {
  name: "CodeAnalysisMetricHistory",
  computed: {
    QueryName() {
      return QueryName;
    },
  },
  components: {
    DynamicQuery,
  },
  methods: {
    onInput(inputs: Inputs) {
      this.inputs = inputs;
    },

    async getHistoryAsCsv(): Promise<void> {
      const baseUrl =
        getApiBaseUrl() +
        `${CODE_ANALYSIS_METRIC_HISTORY_CSV}` +
        `?workloads=${this.inputs.workloads.join(",")}` +
        `&repoGroups=${this.inputs.repoGroups.join(",")}` +
        `&startDate=${this.inputs.startDate}`;

      const metricsCsvUrl = await addAuthQueryParam(baseUrl);
      logger(`Redirecting to metrics CSV: ${metricsCsvUrl}`);
      document.location.href = metricsCsvUrl;
    },
  },
  data() {
    return {
      inputs: {} as Inputs,
    };
  },
};
</script>

// frontend/src/components/CodeAnalysisMetricHistory.tsx
import { DynamicQuery, type DynamicQueryInputs } from "@/components/DynamicQuery";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { addAuthQueryParam, getApiBaseUrl } from "@/api/client";
import { CODE_ANALYSIS_METRIC_HISTORY_CSV } from "@/api/endpoints";
import { useState, useCallback } from "react";
import { getCodeQualityDefaults } from "@/queries/queryDefaults";
import { useI18n } from "@/hooks/useI18n";

export function CodeAnalysisMetricHistory() {
  const { t } = useI18n();
  const [inputs, setInputs] = useState<DynamicQueryInputs>({});

  const handleInputChange = useCallback((newInputs: DynamicQueryInputs) => {
    setInputs(newInputs);
  }, []);

  const getHistoryAsCsv = useCallback(async () => {
    const workloads = inputs.workloads?.join(",") ?? "";
    const repoGroups = inputs.repoGroups?.join(",") ?? "";
    const startDate = inputs.startDate ?? "";

    const baseUrl =
      getApiBaseUrl() +
      CODE_ANALYSIS_METRIC_HISTORY_CSV +
      `?workloads=${workloads}` +
      `&repoGroups=${repoGroups}` +
      `&startDate=${startDate}`;

    const metricsCsvUrl = await addAuthQueryParam(baseUrl);
    console.log(`Redirecting to metrics CSV: ${metricsCsvUrl}`);
    document.location.href = metricsCsvUrl;
  }, [inputs]);

  return (
    <DynamicQuery
      title={t("components:codeAnalysis.historyTitle")}
      subtitle={t("components:codeAnalysis.historyDescription")}
      queryTypes={["code-coverage"]}
      defaultInputs={getCodeQualityDefaults()}
      hideChartSelector={true}
      onInputChange={handleInputChange}
    >
      <Button onClick={getHistoryAsCsv} variant="secondary" className="ml-2">
        <Download className="mr-2 h-4 w-4" />
        {t("components:codeAnalysis.downloadCsv")}
      </Button>
    </DynamicQuery>
  );
}

export default CodeAnalysisMetricHistory;
