// ui/src/components/SecurityVulnerabilities.vue
<template>
  <v-card>
    <v-card-title>Vulnerability report</v-card-title>
    <v-card-subtitle>Security vulnerability information.</v-card-subtitle>

    <v-card-text v-if="!!alert">
      <v-alert :type="alert.type">{{ alert.message }}</v-alert>
    </v-card-text>

    <v-container fluid>
      <v-row>
        <v-col sm="6">
          <v-card-text>
            <DynamicInputs
              @execute="onQuery"
              :operationState="operationState"
              query-name="Security vulnerabilities"
              :query-types="queryTypes"
              :default-inputs="defaultInputs"
              :execute-on-mount="executeOnMount"
            />
          </v-card-text>
        </v-col>
      </v-row>
      <v-row>
        <v-col
          cols="12"
          sm="6"
          lg="4"
          xl="2"
          v-for="outcomes in workloadOutcomes"
          :key="outcomes.key"
        >
          <div class="text-h5 text-center">{{ outcomes.key }}</div>
          <div class="text-h4 text-center">
            {{ Math.round(outcomes.total) }} total
          </div>
          <DoughnutChart :chart-data="outcomes.chartData" />
        </v-col>
      </v-row>
    </v-container>
  </v-card>
</template>

<script lang="ts">
// @ts-nocheck
import DynamicInputs from "@/components/DynamicInputs.vue";
import { executeQuery } from "@/services/query";
import { OperationState } from "@/utils/ui";
import { calculatePercentageByTag } from "@/chart/common";
import { logger } from "@/utils/logger";
import DoughnutChart from "@/components/charts/DoughnutChart.vue";
import { QueryName } from "@/queries/queries";
import { listRepoGroups, listWorkloadIds } from "@/utils/config";
import { sumAllMetricValues } from "@/utils/metrics";
import { createDoughnutChartData } from "@/chart/doughnut";

export default {
  name: "SecurityVulnerabilities",
  components: {
    DoughnutChart,
    DynamicInputs,
  },
  props: {
    workload: {
      type: String,
      default: null,
    },
    executeOnMount: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    async onQuery(rawQueries) {
      this.operationState = OperationState.Busy;
      try {
        const args = rawQueries[0].args;
        this.workloadOutcomes = [];

        let workloads = [];
        if (args.workloads.length === 1 && args.workloads[0] === "all") {
          workloads = listWorkloadIds();
        } else {
          workloads = args.workloads;
        }

        let repoGroups = [];
        if (!args.repoGroups || args.repoGroups.length === 0) {
          repoGroups = listRepoGroups();
        } else {
          repoGroups = args.repoGroups;
        }

        // split into individual queries
        const queries = [];
        for (const workload of workloads) {
          for (const repoGroup of repoGroups) {
            const query = {
              queryName: QueryName.Vulnerabilities,
              args: {
                ...args,
                repoGroups: [repoGroup],
                workloads: [workload],
              },
            };
            queries.push(this.runQuery(query, repoGroup, workload));
          }
        }

        await Promise.all(queries);
        this.operationState = OperationState.Idle;
      } catch (error) {
        console.error("Failed to run queries", error);
        this.alert = {
          type: "error",
          message: error.message,
        };
      } finally {
        this.operationState = OperationState.Idle;
      }
    },
    runQuery: async function (query, repoGroup, workload) {
      logger(`Executing security vulnerabilities query with args`, query.args);
      try {
        const result = await executeQuery(query);

        if (result.size > 0) {
          const percentages = calculatePercentageByTag(result, (tag) => {
            return tag.split("/")[1];
          });
          const chartData = createDoughnutChartData(percentages);

          const total = sumAllMetricValues(result);

          this.workloadOutcomes.push({
            key: `${workload}-${repoGroup}`,
            total,
            chartData,
          });
        } else {
          logger(
            `No security vulnerabilities for:`,
            `${workload}-${repoGroup}`,
          );
        }
      } catch (e) {
        throw new Error(
          `Failed to fetch security vulnerabilities for ${workload}/${repoGroup}: ${e}`,
        );
      }
    },
  },
  data() {
    const workloads = this.workload ? [this.workload] : [];
    return {
      workloadOutcomes: [],
      operationState: OperationState.Idle,
      queryTypes: [QueryName.Vulnerabilities],
      alert: null,
      defaultInputs: {
        workloads,
      },
    };
  },
};
</script>

// frontend/src/components/SecurityVulnerabilities.tsx
import { useState, useCallback } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertCircle } from "lucide-react";
import { DynamicInputs, type QueryArgs } from "@/components/inputs";
import { DoughnutChart } from "@/components/charts";
import { executeQuery } from "@/services/query";
import type { RawQuery } from "@/model/query";
import type { DatedMetrics } from "@/model/metrics";
import { listRepoGroups, listWorkloadIds } from "@/config";
import { useI18n } from "@/hooks/useI18n";

interface WorkloadOutcome {
  key: string;
  total: number;
  chartData: {
    labels: string[];
    datasets: {
      data: number[];
      backgroundColor: string[];
    }[];
  };
}

function calculatePercentageByTag(data: Map<string, DatedMetrics>): Map<string, number> {
  const totals = new Map<string, number>();

  for (const [, datedMetrics] of data) {
    for (const [tag, entry] of datedMetrics.entries) {
      // Use the original tag as the key, not the extracted dimension
      totals.set(tag, (totals.get(tag) || 0) + entry.value);
    }
  }

  return totals;
}

function createDoughnutChartData(percentages: Map<string, number>) {
  const labels = Array.from(percentages.keys());
  const values = Array.from(percentages.values());

  // Map colors based on severity level in tag name
  const getColorForSeverity = (tag: string): string => {
    const lowerTag = tag.toLowerCase();
    if (lowerTag.includes("critical")) return "#dc2626"; // red
    if (lowerTag.includes("high")) return "#f97316"; // orange
    if (lowerTag.includes("medium")) return "#eab308"; // yellow/amber
    if (lowerTag.includes("low")) return "#3b82f6"; // blue (still indicates an issue)
    return "#6b7280"; // gray for unknown
  };

  return {
    labels,
    datasets: [
      {
        data: values,
        backgroundColor: labels.map((label) => getColorForSeverity(label)),
      },
    ],
  };
}

function sumAllMetricValues(data: Map<string, DatedMetrics>): number {
  let total = 0;
  for (const [, datedMetrics] of data) {
    for (const entry of datedMetrics.entries.values()) {
      total += entry.value;
    }
  }
  return total;
}

export interface SecurityVulnerabilitiesProps {
  workload?: string;
  branchNames?: string[];
  executeOnMount?: boolean;
}

export function SecurityVulnerabilities({
  workload,
  branchNames,
  executeOnMount = false,
}: SecurityVulnerabilitiesProps) {
  const { t } = useI18n();
  const [workloadOutcomes, setWorkloadOutcomes] = useState<WorkloadOutcome[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const runQuery = useCallback(
    async (query: RawQuery, repoGroup: string, workloadId: string): Promise<WorkloadOutcome | null> => {
      try {
        const result = await executeQuery(query);

        if (result && result.size > 0) {
          const percentages = calculatePercentageByTag(result);
          const chartData = createDoughnutChartData(percentages);
          const total = sumAllMetricValues(result);

          return {
            key: `${workloadId}-${repoGroup}`,
            total,
            chartData,
          };
        }
        return null;
      } catch (e) {
        throw new Error(`Failed to fetch security vulnerabilities for ${workloadId}/${repoGroup}: ${e}`);
      }
    },
    []
  );

  const handleExecute = useCallback(
    async (rawQueries: RawQuery[]) => {
      setIsLoading(true);
      setError(null);
      setWorkloadOutcomes([]);

      try {
        const args = rawQueries[0]?.args || {};
        const workloads = (args.workloads as string[])?.length > 0 ? (args.workloads as string[]) : listWorkloadIds();

        let repoGroups: string[] = [];
        const inputRepoGroups = args.repoGroups as string[] | undefined;
        if (!inputRepoGroups || inputRepoGroups.length === 0) {
          repoGroups = listRepoGroups();
        } else {
          repoGroups = inputRepoGroups;
        }

        const queries: Promise<WorkloadOutcome | null>[] = [];
        for (const wl of workloads) {
          for (const rg of repoGroups) {
            const query: RawQuery = {
              queryName: "vulnerabilities",
              args: {
                ...args,
                repoGroups: [rg],
                workloads: [wl],
              },
            };
            queries.push(runQuery(query, rg, wl));
          }
        }

        const results = await Promise.all(queries);
        const outcomes = results.filter((r): r is WorkloadOutcome => r !== null);
        setWorkloadOutcomes(outcomes);
      } catch (e) {
        console.error("Failed to run queries", e);
        setError((e as Error).message);
      } finally {
        setIsLoading(false);
      }
    },
    [runQuery]
  );

  const defaultInputs: QueryArgs = {
    workloads: workload ? [workload] : [],
    branchNames: branchNames || [],
  };

  return (
    <Card className="card-elevated">
      <CardHeader className="border-border/50 border-b pb-4">
        <CardTitle>{t("components:securityVulnerabilities.title")}</CardTitle>
        <CardDescription>{t("components:securityVulnerabilities.description")}</CardDescription>
      </CardHeader>

      {error && (
        <CardContent>
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>{t("components:securityVulnerabilities.error")}</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        </CardContent>
      )}

      <CardContent>
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div>
            <DynamicInputs
              queryTypes={["vulnerabilities"]}
              queryName="Security vulnerabilities"
              defaultInputs={defaultInputs}
              isBusy={isLoading}
              executeOnMount={executeOnMount}
              onExecute={handleExecute}
            />
          </div>
        </div>

        {/* Loading skeleton for results */}
        {isLoading && (
          <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="space-y-2 text-center">
                <Skeleton className="mx-auto h-5 w-2/3" />
                <Skeleton className="mx-auto h-8 w-1/2" />
                <Skeleton className="mx-auto h-32 w-32 rounded-full" />
              </div>
            ))}
          </div>
        )}

        {/* Results */}
        {!isLoading && workloadOutcomes.length > 0 && (
          <div className="mt-6 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {workloadOutcomes.map((outcome) => (
              <div key={outcome.key} className="flex flex-col items-center space-y-3">
                <h3 className="max-w-full truncate px-2 text-base font-semibold" title={outcome.key}>
                  {outcome.key}
                </h3>
                <p className="text-3xl font-bold">
                  {t("components:securityVulnerabilities.total", { count: Math.round(outcome.total) })}
                </p>
                <div className="w-full">
                  <DoughnutChart
                    chartData={{
                      labels: outcome.chartData.labels,
                      data: outcome.chartData.datasets[0].data,
                      colors: outcome.chartData.datasets[0].backgroundColor,
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        )}

        {!isLoading && workloadOutcomes.length === 0 && !error && (
          <div className="text-muted-foreground mt-4 py-8 text-center">
            {t("components:securityVulnerabilities.noResults")}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
