// ui/src/components/UploadFile.vue
<template>
  <v-card>
    <v-card-title>Upload vulnerability report</v-card-title>
    <v-card-subtitle>Upload a SARIF format report.</v-card-subtitle>

    <v-card-text v-if="!!alert">
      <AlertMessage :alert="alert" />
    </v-card-text>

    <v-container fluid>
      <v-row>
        <v-col sm="6">
          <v-card-text>
            <WorkloadNames
              :multi-select="false"
              :include-all-option="false"
              defaults=""
              @input="(value) => updateWorkload(value)"
              :disabled="busy"
            />
            <VCombobox
              label="Repo name"
              hint="Override the repo name"
              :multiple="false"
              :items="repoNames"
              v-model="repoName"
            />
            <DatePicker label="Report date" v-model="reportDate" />
            <VFileInput label="SARIF file" v-model="chosenFile" accept=".sarif" :disabled="busy" :multiple="false" />
            <VBtn color="primary" @click.prevent="upload" :disabled="busy || !workload?.length || !chosenFile?.length"
              >Upload
            </VBtn>
          </v-card-text>
        </v-col>
      </v-row>
    </v-container>
  </v-card>
</template>

<script lang="ts" setup>
// @ts-nocheck
import { computed, ref } from "vue";
import { OperationState } from "@/utils/ui";
import WorkloadNames from "@/components/inputs/WorkloadNames.vue";
import { client } from "@/utils/apiClient";
import { VULNERABILITIES } from "@/utils/urls";
import DatePicker from "@/components/DatePicker.vue";
import { getTodayDateOnly } from "@/utils/date";
import { getReposForWorkloadId } from "@/utils/config";
import AlertMessage from "@/components/AlertMessage.vue";
import type { Alert } from "@/utils/ui";

type PersistVulnsQueryParams = {
  workload: string;
  repoName?: string;
  reportDate: string;
};

const operationState = ref(OperationState.Idle);
const chosenFile = ref<File[]>();
const alert = ref<Alert>(null);
const repoNames = ref([]);
const repoName = ref("");
const reportDate = ref(getTodayDateOnly());
const workload = ref("");

const upload = async () => {
  operationState.value = OperationState.Busy;
  try {
    if (!chosenFile.value?.length) {
      alert.value = {
        type: "error",
        message: "No SARIF file selected.",
      };
      return;
    }

    const reader = new FileReader();
    reader.onload = async () => {
      const params: PersistVulnsQueryParams = {
        workload: workload.value,
        repoName: repoName.value,
        reportDate: reportDate.value, //truncateDateOnly(reportDate.value),
      };
      const response = await client.post(VULNERABILITIES, reader.result, {
        headers: {
          "Content-Type": "application/json", //"application/sarif+json",
        },
        params,
      });

      if (response.status === 201) {
        operationState.value = OperationState.Idle;
      } else {
        alert.value = {
          type: "error",
          message: `HTTP ${response.status} uploading SARIF file`,
        };
      }
    };
    reader.readAsArrayBuffer(chosenFile.value[0]);
  } catch (error) {
    console.error("Failed to run queries", error);
    alert.value = {
      type: "error",
      message: error.message,
    };
  } finally {
    operationState.value = OperationState.Idle;
  }
};

const updateWorkload = (workloadId: string) => {
  workload.value = workloadId;
  repoNames.value = getReposForWorkloadId(workloadId);
};

const busy = computed(() => operationState.value === OperationState.Busy);
</script>

// frontend/src/components/UploadFile.tsx
import { useState, useCallback } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Combobox } from "@/components/ui/combobox";
import { WorkloadNames } from "@/components/inputs/WorkloadNames";
import { DatePicker } from "@/components/inputs/DatePicker";
import { AlertMessage, type Alert } from "@/components/AlertMessage";
import { getTodayDateOnly } from "@/utils/date";
import { getReposForWorkloadId } from "@/config";
import client from "@/api/client";
import { VULNERABILITIES } from "@/api/endpoints";
import { useI18n } from "@/hooks/useI18n";

export function UploadFile() {
  const { t } = useI18n();
  const [workload, setWorkload] = useState<string>("");
  const [repoName, setRepoName] = useState<string>("");
  const [repoNames, setRepoNames] = useState<string[]>([]);
  const [reportDate, setReportDate] = useState<Date | undefined>(() => {
    const today = getTodayDateOnly();
    return today ? new Date(today) : undefined;
  });
  const [chosenFile, setChosenFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [alert, setAlert] = useState<Alert>(null);

  const updateWorkload = useCallback((workloadId: string | string[] | null) => {
    const id = Array.isArray(workloadId) ? workloadId[0] : workloadId;
    if (id) {
      setWorkload(id);
      setRepoNames(getReposForWorkloadId(id));
    }
  }, []);

  const onFileChange = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const target = event.target;
    if (target.files && target.files.length > 0) {
      setChosenFile(target.files[0]);
    }
  }, []);

  const upload = useCallback(async () => {
    if (!chosenFile) {
      setAlert({
        type: "error",
        message: "No SARIF file selected.",
      });
      return;
    }

    setBusy(true);
    setAlert(null);

    try {
      const reader = new FileReader();
      reader.onload = async () => {
        try {
          const params = {
            workload,
            repoName,
            reportDate: reportDate?.toISOString().split("T")[0] ?? "",
          };
          // Parse the SARIF JSON so the client can serialize it correctly
          const sarifContent = JSON.parse(reader.result as string);
          const response = await client.post(VULNERABILITIES, sarifContent, {
            headers: {
              "Content-Type": "application/json",
            },
            params,
          });

          if (response.status === 201) {
            setAlert({
              type: "success",
              message: "SARIF file uploaded successfully.",
            });
          } else {
            setAlert({
              type: "error",
              message: `HTTP ${response.status} uploading SARIF file`,
            });
          }
        } catch (error) {
          console.error("Failed to upload SARIF file", error);
          setAlert({
            type: "error",
            message: (error as Error).message,
          });
        } finally {
          setBusy(false);
        }
      };
      reader.readAsText(chosenFile);
    } catch (error) {
      console.error("Failed to read file", error);
      setAlert({
        type: "error",
        message: (error as Error).message,
      });
      setBusy(false);
    }
  }, [chosenFile, workload, repoName, reportDate]);

  return (
    <Card className="card-elevated">
      <CardHeader className="border-border/50 border-b pb-4">
        <CardTitle>{t("components:uploadFile.title")}</CardTitle>
        <CardDescription>{t("components:uploadFile.description")}</CardDescription>
      </CardHeader>

      {alert && (
        <CardContent>
          <AlertMessage alert={alert} />
        </CardContent>
      )}

      <CardContent>
        <div className="max-w-md space-y-4">
          <WorkloadNames multiSelect={false} onChange={updateWorkload} disabled={busy} />
          <Combobox
            value={repoName}
            onChange={(value) => setRepoName((value as string) ?? "")}
            options={repoNames.map((r) => ({ value: r, label: r }))}
            placeholder={t("components:uploadFile.repoName")}
            label={t("components:uploadFile.repoName")}
          />
          <DatePicker label={t("components:uploadFile.reportDate")} value={reportDate} onChange={setReportDate} />
          <div className="space-y-1">
            <Label>{t("components:uploadFile.sarifFile")}</Label>
            <Input type="file" accept=".sarif" disabled={busy} onChange={onFileChange} />
          </div>
          <Button variant="default" onClick={upload} disabled={busy || !workload || !chosenFile}>
            {t("components:uploadFile.upload")}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
