// ui/src/components/Footer.vue
<template>
  <div>
    <v-footer padless>
      <v-col class="text-center text-sm-body-2" cols="12">
        <div class="text--secondary">CodeMetrics version {{ version }}</div>
        <div>
          &copy; {{ new Date().getFullYear() }} —
          <strong>Deloitte Digital</strong>
        </div>
      </v-col>
    </v-footer>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { getBootstrap } from "@/utils/config";

export default defineComponent({
  setup() {
    const appVersion = getBootstrap().apiVersion;
    return {
      version: appVersion,
    };
  },
});
</script>

// frontend/src/components/layout/Footer.tsx
import { getBootstrap } from "@/config";

export function Footer() {
  let version = "unknown";
  try {
    version = getBootstrap().apiVersion;
  } catch {
    // Bootstrap may not be loaded yet
  }

  return (
    <footer className="bg-background/50 border-t">
      <div className="container py-6 text-center">
        <p className="text-muted-foreground mb-1 text-xs">CodeMetrics v{version}</p>
        <p className="text-muted-foreground text-sm">
          &copy; {new Date().getFullYear()} — <strong className="font-semibold">Deloitte Digital</strong>
        </p>
      </div>
    </footer>
  );
}
