// frontend/src/components/inputs/JobNames.tsx
import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Combobox } from "@/components/ui/combobox";
import { getJobsForWorkloadId, listWorkloadIds } from "@/config";

export interface JobNamesProps {
  /** Current selected values (controlled) */
  value?: string[];
  /** @deprecated Use value instead. Fallback for uncontrolled usage. */
  defaults?: string[];
  /** Optional: filter jobs to specific workloads */
  workloadIds?: string[];
  disabled?: boolean;
  onChange?: (value: string[]) => void;
}

export function JobNames({ value, defaults = [], workloadIds = [], disabled = false, onChange }: JobNamesProps) {
  const { t } = useTranslation();
  // Get all job names from workloads, or all workloads if none specified
  const options = useMemo<string[]>(() => {
    const workloadIdsToQuery = workloadIds.length > 0 ? workloadIds : listWorkloadIds();
    const allJobs = workloadIdsToQuery.flatMap((workloadId) => getJobsForWorkloadId(workloadId));
    return [...new Set(allJobs)].sort();
  }, [workloadIds]);

  // Use controlled value, fall back to defaults for backwards compatibility
  const selectedValue = value ?? defaults;

  const handleChange = (newValue: string | string[] | null) => {
    const arrayValue = Array.isArray(newValue) ? newValue : newValue ? [newValue] : [];
    onChange?.(arrayValue);
  };

  return (
    <div className="space-y-1">
      <Combobox
        label={t("components:inputs.labels.jobNames")}
        value={selectedValue}
        options={options.map((job: string) => ({ value: job, label: job }))}
        placeholder={t("components:inputs.selectJobNames")}
        disabled={disabled}
        multiple
        onChange={handleChange}
      />
    </div>
  );
}

// ui/src/components/inputs/JobNames.vue
<template>
  <v-combobox
    name="jobNames"
    v-model="jobNames"
    :items="options"
    :disabled="busy"
    label="Job Names"
    multiple
    small-chips
    @update:model-value="onChange"
    hide-details
  />
</template>

<script lang="ts" setup>
import { computed, onMounted, ref, watch } from "vue";
import { OperationState } from "@/utils/ui";
import { getJobsForWorkloadId, listWorkloadIds } from "@/utils/config";
import { getDefaultValue, InputType } from "@/queries/inputs";
import type { CommonInputProps } from "@/components/inputs/CommonInputProps";

type TProps = CommonInputProps<string[]> & {
  workloadIds?: string[];
  operationState?: OperationState;
};

const props = withDefaults(defineProps<TProps>(), {
  defaults: () => getDefaultValue<string[]>(InputType.JOB_NAMES),
  workloadIds: () => [],
  operationState: OperationState.Idle,
});

const emit = defineEmits(["input"]);

const options = ref<string[]>([]);
const jobNames = ref(props.defaults);

const busy = computed(() => {
  return props.operationState === OperationState.Busy;
});

const updateOptions = () => {
  // If no workloads are provided, get all jobs from all workloads
  const workloadIdsToQuery =
    !props.workloadIds || props.workloadIds.length === 0 ? listWorkloadIds() : props.workloadIds;

  const allJobs = workloadIdsToQuery.flatMap((workloadId) => getJobsForWorkloadId(workloadId));
  options.value = [...new Set(allJobs)].sort();
};

const onChange = () => {
  emit("input", jobNames.value);
};

watch(() => props.workloadIds, updateOptions);

onMounted(() => {
  updateOptions();
  onChange();
});
</script>
