// frontend/src/pages/DependencyAlerts.tsx
import { useSearchParams } from "react-router-dom";
import { PageBreadcrumbs } from "@/components/layout";
import { DependencyAlertsList } from "@/components/dependencyAlerts";
import { Paths } from "@/router/paths";
import { useI18n } from "@/hooks/useI18n";
import { getWorkloadName } from "@/services/workload";

export default function DependencyAlerts() {
  const { t } = useI18n();
  const [searchParams] = useSearchParams();
  const workloadId = searchParams.get("workloadId") ?? undefined;
  const executeImmediately = searchParams.get("executeImmediately") === "true";
  const repoName = searchParams.get("repoName") ?? undefined;
  const repoGroupsParam = searchParams.get("repoGroups");
  const repoGroups = repoGroupsParam ? repoGroupsParam.split(",") : [];
  const workloadName = workloadId ? getWorkloadName(workloadId) : undefined;
  const breadcrumbs = workloadId
    ? [
        { label: t("nav:workload"), to: Paths.Workloads },
        { label: workloadName, to: `${Paths.Workloads}/${workloadId}` },
        { label: t("nav:workloadDependencyAlerts") },
      ]
    : [{ label: t("nav:programme"), to: Paths.Program }, { label: t("nav:workloadDependencyAlerts") }];

  const workloadIds = workloadId ? [workloadId] : [];

  return (
    <div>
      {/* Header */}
      <section className="header-section py-8">
        <div className="relative z-10 container mx-auto px-4">
          <PageBreadcrumbs items={breadcrumbs} />
          <h2 className="mt-2 text-3xl font-bold">{t("pages:dependencyAlerts.title")}</h2>
          <p className="text-muted-foreground mt-1">{t("pages:dependencyAlerts.description")}</p>
        </div>
      </section>

      {/* Content */}
      <div className="container mx-auto px-4 py-8">
        <DependencyAlertsList
          workloadIds={workloadIds}
          repoName={repoName}
          repoGroups={repoGroups}
          executeOnMount={executeImmediately}
        />
      </div>
    </div>
  );
}

// ui/src/pages/DependencyAlerts.vue
<template>
  <div>
    <v-sheet color="accent">
      <v-container>
        <v-row>
          <v-col class="pb-8">
            <v-breadcrumbs :items="items"></v-breadcrumbs>
            <h2 class="text-h2">Dependency Alerts</h2>
          </v-col>
        </v-row>
      </v-container>
    </v-sheet>

    <v-container>
      <v-row>
        <v-col>
          <DependencyAlertsList
            :workload-ids="workloadIds"
            :repo-name="repoNameString"
            :repo-groups="repoGroupsArray"
            :execute-on-mount="executeImmediately"
          />
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<script lang="ts" setup>
import { useI18n } from "vue-i18n";
import { useRoute } from "vue-router";
import DependencyAlertsList from "@/components/dependencyAlerts/DependencyAlertsList.vue";
import { Paths } from "@/router/paths";
import { computed } from "vue";

const { t } = useI18n();
const route = useRoute();

const { workloadId, executeImmediately: queryExecuteImmediately, repoName, repoGroups: queryRepoGroups } = route.query;

const executeImmediately = queryExecuteImmediately === "true";

const workloadIds = computed(() => {
  if (!workloadId) return [];
  return Array.isArray(workloadId)
    ? workloadId.filter((id): id is string => typeof id === "string")
    : [workloadId as string];
});

const repoGroupsArray = computed(() => {
  if (!queryRepoGroups) return [];
  return Array.isArray(queryRepoGroups)
    ? queryRepoGroups.filter((rg): rg is string => typeof rg === "string")
    : [queryRepoGroups as string];
});

const repoNameString = computed(() => {
  if (!repoName) return undefined;
  return typeof repoName === "string" ? repoName : undefined;
});

const items = workloadId
  ? [
      {
        title: "Workloads",
        to: Paths.Workloads,
      },
      {
        title: workloadId as string,
        to: `${Paths.Workloads}/${workloadId}`,
      },
      {
        title: "Dependency Alerts",
        to: Paths.WorkloadDependencyAlerts,
      },
    ]
  : [
      {
        title: t("nav.program"),
        to: Paths.Program,
      },
      {
        title: "Dependency Alerts",
        to: Paths.ProgramDependencyAlerts,
      },
    ];
</script>
