// frontend/src/pages/Narratives.tsx
import { useSearchParams } from "react-router-dom";
import { PageBreadcrumbs } from "@/components/layout";
import { Paths } from "@/router/paths";
import { RepoChanges } from "@/components/RepoChanges";
import { useI18n } from "@/hooks/useI18n";
import { getWorkloadName } from "@/services/workload";

export default function Narratives() {
  const { t } = useI18n();
  const [searchParams] = useSearchParams();
  const workloadId = searchParams.get("workloadId");
  const executeImmediately = searchParams.get("executeImmediately") === "true";
  const workloadName = workloadId ? getWorkloadName(workloadId) : undefined;
  const breadcrumbs = workloadId
    ? [
        { label: t("nav:workload"), to: Paths.Workloads },
        { label: workloadName, to: `${Paths.Workloads}/${workloadId}` },
        { label: t("nav:changes") },
      ]
    : [{ label: t("nav:programme"), to: Paths.Program }, { label: t("nav:changes") }];

  return (
    <div>
      {/* Header */}
      <section className="header-section py-8">
        <div className="relative z-10 container mx-auto px-4">
          <PageBreadcrumbs items={breadcrumbs} />
          <h2 className="mt-2 text-3xl font-bold">{t("pages:narratives.title")}</h2>
        </div>
      </section>

      {/* Content */}
      <div className="container mx-auto px-4 py-8">
        {workloadId ? (
          <RepoChanges workload={workloadId} executeOnMount={executeImmediately} />
        ) : (
          <RepoChanges executeOnMount={executeImmediately} />
        )}
      </div>
    </div>
  );
}

// ui/src/pages/Narratives.vue
<template>
  <div>
    <v-sheet color="accent">
      <v-container>
        <v-row>
          <v-col class="pb-8">
            <v-breadcrumbs :items="items"></v-breadcrumbs>
            <h2 class="text-h2">{{ $t("nav.changes") }}</h2>
          </v-col>
        </v-row>
      </v-container>
    </v-sheet>

    <v-container>
      <v-row>
        <v-col>
          <RepoChanges
            v-if="!Array.isArray(workloadId)"
            :workload="workloadId as string"
            :executeOnMount="executeImmediately"
          />
          <p v-else>
            Multiple workloads provided in query, please provide just one.
          </p>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<script lang="ts" setup>
import { useI18n } from "vue-i18n";
import { useRoute } from "vue-router";
import RepoChanges from "@/components/RepoChanges.vue";
import { Paths } from "@/router/paths";

const { t } = useI18n();
const route = useRoute();

const { workloadId, executeImmediately: queryExecuteImmediately } =
  route.query as { workloadId: string; executeImmediately: string };
const executeImmediately = queryExecuteImmediately === "true";

const items = workloadId
  ? [
      {
        title: "Workloads",
        to: Paths.Workloads,
      },
      {
        title: workloadId,
        to: `${Paths.Workloads}/${workloadId}`,
      },
      {
        title: t("nav.changes"),
        to: `${Paths.Workloads}/${workloadId}`,
      },
    ]
  : [
      {
        title: t("nav.program"),
        to: Paths.Program,
      },
      {
        title: t("nav.changes"),
        to: Paths.ProgramMetrics,
      },
    ];
</script>
