// frontend/src/pages/QualityGates.tsx
import { useState, useMemo } from "react";
import { useI18n } from "@/hooks/useI18n";
import { useParams } from "react-router-dom";
import { capitalize } from "@/utils/string";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PageBreadcrumbs } from "@/components/layout";
import {
  AlertCircle,
  ChevronUp,
  ChevronDown,
  ClipboardCheck,
  ClipboardX,
  ShieldCheck,
  ShieldOff,
  ShieldAlert,
  ExternalLink,
} from "lucide-react";
import { useQualityGates, type TGate, type TPhase, type TRepo } from "@/queries/useQualityGates";
import { Paths } from "@/router/paths";
import { listWorkloadIds } from "@/config";
import { getWorkloadName } from "@/services/workload";

interface FormattedData {
  id: string;
  message: string;
  service?: string;
  repo: string;
  repoLink: string;
  qualityGates?: TGate;
}

function getVariantClass(variant: string): string {
  const variantMap: Record<string, string> = {
    success: "bg-green-600",
    warning: "bg-yellow-600",
    error: "bg-red-600",
    danger: "bg-red-600",
    info: "bg-blue-600",
    no_data: "bg-zinc-600",
  };
  return variantMap[variant] || "bg-zinc-600";
}

function hasQualityGate(qualityGate: TPhase[]): boolean {
  return !!qualityGate.find((qg) => qg.gates.length);
}

function getQualityGateSummaries(repos: TRepo[], t: (key: string) => string): FormattedData[] {
  if (!repos) return [];
  const fd: FormattedData[] = [];
  repos.forEach((manifest) => {
    if (!manifest.services?.length) {
      fd.push({
        id: manifest.repo || "",
        message: !manifest.services ? t("pages:qualityGates.noManifest") : t("pages:qualityGates.noServiceMatch"),
        repo: manifest.repo || "",
        repoLink: manifest.repoLink || "",
      });
      return;
    }

    manifest.services.forEach((manifestService) => {
      fd.push({
        id: `${manifestService["service-tag"]}-${manifest.repo}`,
        message: "Success",
        service: manifestService["service-tag"],
        repo: manifest.repo || "",
        repoLink: manifest.repoLink || "",
        qualityGates: manifestService["quality-gates"],
      });
    });
  });

  return fd;
}

export default function QualityGates() {
  const { t } = useI18n();
  const { workloadId } = useParams<{ workloadId?: string }>();
  const [openDetails, setOpenDetails] = useState<Set<string>>(new Set());
  const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set());
  const workloadName = workloadId ? getWorkloadName(workloadId) : undefined;
  const breadcrumbs = workloadId
    ? [
        { label: t("pages:qualityGates.breadcrumb.workloads"), to: Paths.Workloads },
        { label: workloadName ?? workloadId, to: `${Paths.Workloads}/${workloadId}` },
        { label: t("pages:qualityGates.breadcrumb.qualityGates") },
      ]
    : [
        { label: t("pages:qualityGates.breadcrumb.programme"), to: Paths.Program },
        { label: t("pages:qualityGates.breadcrumb.qualityGates") },
      ];

  // Get all workloads if none specified
  const queryWorkloads = useMemo(() => {
    if (workloadId) return [workloadId];
    try {
      return listWorkloadIds();
    } catch {
      return [];
    }
  }, [workloadId]);

  const { data, error, isError, isLoading } = useQualityGates({ workloads: queryWorkloads }, queryWorkloads.length > 0);

  const toggleDetails = (key: string) => {
    setOpenDetails((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(key)) {
        newSet.delete(key);
      } else {
        newSet.add(key);
      }
      return newSet;
    });
  };

  const toggleRowExpand = (id: string) => {
    setExpandedRows((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        newSet.add(id);
      }
      return newSet;
    });
  };

  return (
    <div>
      <div className="header-section">
        <div className="relative z-10 container mx-auto px-4 py-8">
          <PageBreadcrumbs items={breadcrumbs} />
          <h2 className="mt-4 text-3xl font-bold">{t("pages:qualityGates.title")}</h2>
          <p className="py-1 text-base">{t("pages:qualityGates.description")}</p>
        </div>
      </div>

      {isError && (
        <div className="container mx-auto px-4 py-4">
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertTitle>{t("pages:qualityGates.error")}</AlertTitle>
            <AlertDescription>{(error || "").toString()}</AlertDescription>
          </Alert>
        </div>
      )}

      {isLoading && (
        <div className="container mx-auto px-4 py-4">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
            {[1, 2, 3, 4, 5, 6].map((i) => (
              <Card key={i}>
                <Skeleton className="h-12 w-full" />
                <CardContent className="p-4">
                  <Skeleton className="mb-2 h-8 w-3/4" />
                  <Skeleton className="h-4 w-1/2" />
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {data && data.length > 0 && (
        <div className="container mx-auto px-4 py-4">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
            {data.map((workload, workloadIndex) =>
              workload.repoGroups?.map((repoGroup, repoGroupIndex) => (
                <Card key={`${workloadIndex}-${repoGroupIndex}`}>
                  <div className={`p-4 text-white ${getVariantClass(repoGroup.headline.variant)}`}>
                    <h3 className="text-lg font-semibold">
                      {getWorkloadName(workload.workloadId)} / {repoGroup.repoGroup}
                    </h3>
                  </div>

                  <CardContent className="p-4">
                    <h4 className="text-2xl font-bold">
                      {repoGroup.headline.denominator > 0 ? (
                        <>
                          {t("pages:qualityGates.implemented", {
                            current: repoGroup.headline.numerator,
                            total: repoGroup.headline.denominator,
                          })}
                        </>
                      ) : (
                        t("pages:qualityGates.noData")
                      )}
                    </h4>

                    {repoGroup.headline.missing > 0 && (
                      <p className="text-muted-foreground mt-1 text-sm">
                        {t("pages:qualityGates.missingData", { count: repoGroup.headline.missing })}
                      </p>
                    )}

                    <p className="mt-2">
                      <span className="text-muted-foreground">{t("pages:qualityGates.numberOfRepos")} </span>
                      <strong>{repoGroup.repos.length}</strong>
                    </p>
                  </CardContent>

                  <CardFooter className="flex justify-between border-t p-4">
                    <Button variant="ghost">{t("pages:qualityGates.details")}</Button>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => toggleDetails(`${workload.workloadId}-${repoGroup.repoGroup}`)}
                    >
                      {openDetails.has(`${workload.workloadId}-${repoGroup.repoGroup}`) ? (
                        <ChevronUp className="h-4 w-4" />
                      ) : (
                        <ChevronDown className="h-4 w-4" />
                      )}
                    </Button>
                  </CardFooter>

                  {openDetails.has(`${workload.workloadId}-${repoGroup.repoGroup}`) && (
                    <>
                      <Separator />
                      <CardContent className="p-4">
                        <Table>
                          <TableHeader>
                            <TableRow>
                              <TableHead>{t("pages:qualityGates.colHeaders.repository")}</TableHead>
                              <TableHead>{t("pages:qualityGates.colHeaders.qualityGates")}</TableHead>
                              <TableHead></TableHead>
                            </TableRow>
                          </TableHeader>
                          <TableBody>
                            {getQualityGateSummaries(repoGroup.repos, t).map((item) => (
                              <>
                                <TableRow key={item.id}>
                                  <TableCell>
                                    <a
                                      href={item.repoLink}
                                      target="_blank"
                                      rel="noreferrer"
                                      className="text-primary inline-flex items-center gap-1 hover:underline"
                                    >
                                      {item.repo}
                                      <ExternalLink className="h-3 w-3" />
                                    </a>
                                  </TableCell>
                                  <TableCell>
                                    {item.qualityGates && (
                                      <div className="flex flex-wrap gap-1">
                                        {Object.entries(item.qualityGates).map(([qualityGateName, phases]) => (
                                          <Badge
                                            key={qualityGateName}
                                            variant={hasQualityGate(phases) ? "default" : "destructive"}
                                            className="text-xs"
                                          >
                                            {hasQualityGate(phases) ? (
                                              <ClipboardCheck className="mr-1 h-3 w-3" />
                                            ) : (
                                              <ClipboardX className="mr-1 h-3 w-3" />
                                            )}
                                            {capitalize(qualityGateName)}
                                          </Badge>
                                        ))}
                                      </div>
                                    )}
                                  </TableCell>
                                  <TableCell>
                                    {item.service ? (
                                      <Button variant="outline" size="sm" onClick={() => toggleRowExpand(item.id)}>
                                        {expandedRows.has(item.id)
                                          ? t("pages:qualityGates.collapse")
                                          : t("pages:qualityGates.moreInfo")}
                                        {expandedRows.has(item.id) ? (
                                          <ChevronUp className="ml-1 h-4 w-4" />
                                        ) : (
                                          <ChevronDown className="ml-1 h-4 w-4" />
                                        )}
                                      </Button>
                                    ) : (
                                      <p className="text-muted-foreground text-sm">{item.message}</p>
                                    )}
                                  </TableCell>
                                </TableRow>
                                {expandedRows.has(item.id) && item.qualityGates && (
                                  <TableRow key={`${item.id}-expanded`}>
                                    <TableCell colSpan={3} className="p-2">
                                      <div className="bg-muted/50 rounded-lg border p-4">
                                        <Table>
                                          <TableHeader>
                                            <TableRow>
                                              <TableHead></TableHead>
                                              {Object.values(item.qualityGates)[0]?.map((phase) => (
                                                <TableHead key={phase.phase}>{capitalize(phase.phase)}</TableHead>
                                              ))}
                                            </TableRow>
                                          </TableHeader>
                                          <TableBody>
                                            {Object.entries(item.qualityGates).map(
                                              ([qualityGateName, qualityGatePhases]) => (
                                                <TableRow key={qualityGateName}>
                                                  <TableCell>{capitalize(qualityGateName)}</TableCell>
                                                  {qualityGatePhases.map((phase, phaseIdx) => (
                                                    <TableCell key={phaseIdx} className="align-top">
                                                      {phase.gates.map((job, jobIdx) => (
                                                        <dl key={jobIdx} className="mb-2 text-xs">
                                                          <div className="flex gap-1">
                                                            <dt>{t("pages:qualityGates.colHeaders.provider")}</dt>
                                                            <dd className="font-bold">{job.provider}</dd>
                                                          </div>
                                                          <div className="flex gap-1">
                                                            <dt>{t("pages:qualityGates.colHeaders.file")}</dt>
                                                            <dd className="font-bold">
                                                              <a
                                                                href={job.config.fileURL}
                                                                className="text-primary hover:underline"
                                                              >
                                                                {job.config.file}
                                                              </a>
                                                            </dd>
                                                          </div>
                                                          <div className="flex gap-1">
                                                            <dt>{t("pages:qualityGates.colHeaders.path")}</dt>
                                                            <dd className="font-bold">{job.config.path}</dd>
                                                          </div>
                                                          <div className="flex items-center gap-1">
                                                            <dt>{t("pages:qualityGates.colHeaders.enforced")}</dt>
                                                            <dd>
                                                              {job.isRequiredStatusCheck === true ? (
                                                                <ShieldCheck className="text-primary h-4 w-4" />
                                                              ) : job.isRequiredStatusCheck === false ? (
                                                                <ShieldOff className="text-muted-foreground h-4 w-4" />
                                                              ) : (
                                                                <ShieldAlert className="h-4 w-4 text-yellow-500" />
                                                              )}
                                                            </dd>
                                                          </div>
                                                        </dl>
                                                      ))}
                                                    </TableCell>
                                                  ))}
                                                </TableRow>
                                              )
                                            )}
                                          </TableBody>
                                        </Table>
                                      </div>
                                    </TableCell>
                                  </TableRow>
                                )}
                              </>
                            ))}
                          </TableBody>
                        </Table>
                      </CardContent>
                    </>
                  )}
                </Card>
              ))
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// ui/src/pages/QualityGates.vue
<template>
  <v-sheet color="accent">
    <v-container>
      <v-row>
        <v-col class="pb-8">
          <v-breadcrumbs :items="items"></v-breadcrumbs>
          <h2 class="text-h2">{{ $t("nav.qualityGates") }}</h2>
          <p class="text-body-1 py-1">
            Quality Gates are automated checks ensuring code meets quality standards before progressing to higher
            environments. These gates, configured per service and repository, verify successful test completion, code
            analysis, and security scans, ensuring only high-quality code reaches production.
          </p>
        </v-col>
      </v-row>
    </v-container>
  </v-sheet>

  <v-container v-if="isError">
    <v-row>
      <v-col>
        <v-alert :text="(error || '').toString()" type="error" />
      </v-col>
    </v-row>
  </v-container>

  <v-container fluid v-if="isLoading">
    <v-row :cols="12" :sm="6" :md="4" :lg="3" :xl="2">
      <v-col :cols="12" :sm="6" :xl="4">
        <v-skeleton-loader class="mx-auto border" type="image, article"></v-skeleton-loader>
      </v-col>
      <v-col :cols="12" :sm="6" :xl="4">
        <v-skeleton-loader class="mx-auto border" type="image, article"></v-skeleton-loader>
      </v-col>
      <v-col :cols="12" :sm="6" :xl="4">
        <v-skeleton-loader class="mx-auto border" type="image, article"></v-skeleton-loader>
      </v-col>
      <v-col :cols="12" :sm="6" :xl="4">
        <v-skeleton-loader class="mx-auto border" type="image, article"></v-skeleton-loader>
      </v-col>
      <v-col :cols="12" :sm="6" :xl="4">
        <v-skeleton-loader class="mx-auto border" type="image, article"></v-skeleton-loader>
      </v-col>
      <v-col :cols="12" :sm="6" :xl="4">
        <v-skeleton-loader class="mx-auto border" type="image, article"></v-skeleton-loader>
      </v-col>
    </v-row>
  </v-container>

  <v-container fluid v-if="data?.length">
    <v-row :cols="12" :sm="6" :md="4" :lg="3" :xl="2">
      <template v-for="(workload, workloadIndex) in data" :key="workloadIndex">
        <v-col
          v-for="(repoGroup, repoGroupIndex) in workload.repoGroups"
          :key="repoGroupIndex"
          :cols="12"
          :sm="6"
          :xl="4"
        >
          <v-card>
            <v-sheet :color="convertVariantToColour(repoGroup.headline.variant)">
              <v-card-title class="white--text">{{ workload.workloadId }} / {{ repoGroup.repoGroup }}</v-card-title>
            </v-sheet>

            <div>
              <v-card-title class="text-h4">
                <template v-if="repoGroup.headline.denominator > 0"
                  >{{ repoGroup.headline.numerator }} of {{ repoGroup.headline.denominator }} implemented</template
                >
                <template v-else>No data</template>
              </v-card-title>

              <div v-if="repoGroup.headline.missing > 0">
                <v-card-subtitle>{{ repoGroup.headline.missing }} repo(s) missing data</v-card-subtitle>
              </div>
            </div>

            <v-card-text>
              <span class="text--secondary">Number of repos: </span>
              <strong>{{ repoGroup.repos.length }}</strong>
            </v-card-text>

            <v-card-actions>
              <v-btn text="Details"></v-btn>

              <v-spacer></v-spacer>

              <v-btn
                :icon="
                  openDetails.has(`${workload.workloadId}-${repoGroup.repoGroup}`)
                    ? 'mdi-chevron-up'
                    : 'mdi-chevron-down'
                "
                @click="
                  openDetails.has(`${workload.workloadId}-${repoGroup.repoGroup}`)
                    ? openDetails.delete(`${workload.workloadId}-${repoGroup.repoGroup}`)
                    : openDetails.add(`${workload.workloadId}-${repoGroup.repoGroup}`)
                "
              ></v-btn>
            </v-card-actions>

            <v-expand-transition>
              <div v-show="openDetails.has(`${workload.workloadId}-${repoGroup.repoGroup}`)">
                <v-divider></v-divider>

                <v-card-text>
                  <v-data-table
                    :headers="REPO_COLUMN_HEADERS"
                    :items="getQualityGateSummaries(repoGroup.repos)"
                    :items-per-page="-1"
                    :loading="isLoading"
                    hide-default-footer
                    item-value="id"
                    show-expand
                  >
                    <template v-slot:item.data-table-expand="{ internalItem, isExpanded, toggleExpand }">
                      <v-btn
                        v-if="internalItem.raw.service"
                        :append-icon="isExpanded(internalItem) ? 'mdi-chevron-up' : 'mdi-chevron-down'"
                        :text="isExpanded(internalItem) ? 'Collapse' : 'More info'"
                        class="text-none"
                        color="medium-emphasis"
                        size="small"
                        variant="text"
                        width="105"
                        border
                        slim
                        @click="toggleExpand(internalItem)"
                      ></v-btn>
                      <p v-else>{{ internalItem.raw.message }}</p>
                    </template>

                    <template v-slot:item.repo="{ item }">
                      <a :href="item.repoLink" target="_BLANK">{{ item.repo }}</a>
                    </template>

                    <template v-slot:item.qualityGates="{ item }">
                      <v-chip
                        v-if="item.qualityGates"
                        v-for="qualityGateName in Object.keys(item.qualityGates)"
                        :append-icon="
                          hasQualityGate(item.qualityGates[qualityGateName])
                            ? 'mdi-clipboard-check'
                            : 'mdi-clipboard-text-off-outline'
                        "
                        :color="hasQualityGate(item.qualityGates[qualityGateName]) ? 'green' : 'red'"
                        class="ma-1"
                        size="x-small"
                        variant="outlined"
                        >{{ capitalize(qualityGateName) }}</v-chip
                      >
                    </template>

                    <template v-slot:expanded-row="{ columns, item }">
                      <tr>
                        <td :colspan="columns.length" class="py-2">
                          <v-sheet rounded="lg" border>
                            <v-table v-if="item.qualityGates" density="compact">
                              <tbody class="bg-surface-light">
                                <tr>
                                  <th />
                                  <th
                                    v-for="qualityGateName in Object.values(item.qualityGates)[0].map((qg) => qg.phase)"
                                  >
                                    {{ capitalize(qualityGateName) }}
                                  </th>
                                </tr>
                              </tbody>

                              <tbody>
                                <tr v-for="[qualityGateName, qualityGatePhases] in Object.entries(item.qualityGates)">
                                  <td>{{ capitalize(qualityGateName) }}</td>
                                  <td v-for="phase in qualityGatePhases" class="quality-gate-details-cell">
                                    <dl class="quality-gate-details" v-for="job in phase.gates">
                                      <div>
                                        <dt>Provider:</dt>
                                        <dd>{{ job.provider }}</dd>
                                      </div>
                                      <div>
                                        <dt>File:</dt>
                                        <dd>
                                          <a :href="job.config.fileURL">{{ job.config.file }}</a>
                                        </dd>
                                      </div>
                                      <div>
                                        <dt>Path:</dt>
                                        <dd>{{ job.config.path }}</dd>
                                      </div>
                                      <div>
                                        <dt>Enforced:</dt>
                                        <dd>
                                          <v-icon
                                            color="primary"
                                            :icon="getRequiredStatusCheckIcon(job.isRequiredStatusCheck)"
                                          ></v-icon>
                                        </dd>
                                      </div>
                                    </dl>
                                  </td>
                                </tr>
                              </tbody>
                            </v-table>
                            <div v-else>{{ item.message }}</div>
                          </v-sheet>
                        </td>
                      </tr>
                    </template>
                  </v-data-table>
                </v-card-text>
              </div>
            </v-expand-transition>
          </v-card>
        </v-col>
      </template>
    </v-row>
  </v-container>
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRoute } from "vue-router";
import { capitalize, remove } from "lodash";
import { Paths } from "@/router/paths";
import { useQualityGates, type TGate, type TPhase, type TRepo } from "@/vue-queries/qualityGates";
import { convertVariantToColour } from "@/utils/colours";

const route = useRoute();
const { t } = useI18n();

const workloadId = computed(() => {
  if (!route.params.workloadId) return;
  if (Array.isArray(route.params.workloadId)) return route.params.workloadId[0];
  return route.params.workloadId;
});

const items = workloadId.value
  ? [
      {
        title: "Workloads",
        to: Paths.Workloads,
      },
      {
        title: capitalize(workloadId.value),
        to: `${Paths.Workloads}/${workloadId.value}`,
      },
      {
        title: t("nav.qualityGates"),
        to: `${Paths.Workloads}/${workloadId.value}`,
      },
    ]
  : [
      {
        title: t("nav.program"),
        to: Paths.Program,
      },
      {
        title: t("nav.qualityGates"),
        to: Paths.ProgramQualityGates,
      },
    ];

const openDetails = ref(new Set());

const { data, error, isError, isLoading } = useQualityGates({
  workloads: workloadId.value ? [workloadId.value] : [],
});

type FormattedData = {
  id: string;
  message: string;
  service?: string;
  repo: string;
  repoLink: string;
  qualityGates?: TGate;
}[];

const getQualityGateSummaries = (repos: TRepo[]) => {
  if (!repos) return undefined;
  const fd: FormattedData = [];
  repos.forEach((manifest) => {
    if (!manifest.services || !manifest.services.length) {
      fd.push({
        id: manifest.repo || "",
        message: !manifest.services
          ? "No manifest found in this repo."
          : "No service in the manifest matches this repo group.",
        repo: manifest.repo || "",
        repoLink: manifest.repoLink || "",
      });
      return;
    }

    manifest.services.forEach((manifestService) => {
      fd.push({
        id: `${manifestService["service-tag"]}-${manifest.repo}`,
        message: "Success",
        service: manifestService["service-tag"],
        repo: manifest.repo || "",
        repoLink: manifest.repoLink || "",
        qualityGates: manifestService["quality-gates"],
      });
    });
  });

  return fd;
};

const REPO_COLUMN_HEADERS = [
  {
    title: "Repo",
    key: "repo",
  },
  {
    title: "Quality Gates",
    key: "qualityGates",
  },
];

function getRequiredStatusCheckIcon(isRequiredStatusCheck?: boolean) {
  if (isRequiredStatusCheck === true) return "mdi-shield-check";
  if (isRequiredStatusCheck === false) return "mdi-shield-off-outline";
  return "mdi-shield-alert-outline";
}

function hasQualityGate(qualityGate: TPhase[]) {
  return !!qualityGate.find((qg) => qg.gates.length);
}
</script>

<style lang="scss" scoped>
.quality-gate-details-cell {
  vertical-align: top;
}

.quality-gate-details {
  font-size: 12px;
  margin-bottom: 8px;

  & > div {
    display: flex;
    gap: 4px;
  }

  & dd {
    font-weight: 700;
  }
}
</style>
