// frontend/src/components/CodeHotspots.tsx
import { useState, useMemo, useCallback } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Label } from "@/components/ui/label";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Loader2, AlertCircle, Info, TableIcon, LayoutGrid } from "lucide-react";
import { WorkloadNames, DatePicker } from "@/components/inputs";
import { useCodeHotspots, type RepoData } from "@/queries/useCodeHotspots";
import { useIssueTypes } from "@/queries/useIssueTypes";
import { Combobox } from "@/components/ui/combobox";
import { TreemapChart } from "@/components/charts/TreemapChart";
import { getOffsetDate, truncateDateOnly } from "@/utils/date";
import { useI18n } from "@/hooks/useI18n";

export interface CodeHotspotsProps {
  workload?: string;
  executeOnMount?: boolean;
}

export function CodeHotspots({ workload: initialWorkload, executeOnMount = false }: CodeHotspotsProps) {
  const { t } = useI18n();
  const [workloadValue, setWorkloadValue] = useState<string | null>(initialWorkload ?? null);
  const [startDate, setStartDate] = useState<Date | undefined>(() => new Date(truncateDateOnly(getOffsetDate(-30))));
  const [issueTypes, setIssueTypes] = useState<string[]>([]);
  const [shouldFetch, setShouldFetch] = useState(executeOnMount);
  const [viewMode, setViewMode] = useState<"table" | "heatmap">("heatmap");

  const headers = [
    { title: t("components:codeHotspots.headers.filePath"), key: "path" },
    { title: t("components:codeHotspots.headers.issueRelatedChanges"), key: "count" },
    { title: t("components:codeHotspots.headers.tickets"), key: "issueLinks" },
    { title: t("components:codeHotspots.headers.testCoverage"), key: "coverage" },
  ];

  const { data: issueTypeData } = useIssueTypes(workloadValue);

  // Reset selected issue types when workload changes by tracking workload
  const [lastWorkload, setLastWorkload] = useState<string | undefined>(workloadValue);
  if (lastWorkload !== workloadValue) {
    setLastWorkload(workloadValue);
    setIssueTypes([]);
  }

  const issueTypeOptions = useMemo(() => {
    if (!issueTypeData) return [];
    return issueTypeData.map((type) => ({ value: type, label: type }));
  }, [issueTypeData]);

  const request = useMemo(
    () => ({
      workload: workloadValue,
      startDate: startDate?.toISOString().split("T")[0] ?? "",
      issueTypes: issueTypes.length > 0 ? issueTypes : undefined,
    }),
    [workloadValue, startDate, issueTypes]
  );

  const { data, isError, error, isFetching, refetch } = useCodeHotspots(request, shouldFetch && !!workloadValue);

  const handleWorkloadChange = useCallback((value: string | string[] | null) => {
    const newValue = Array.isArray(value) ? value[0] : value;
    setWorkloadValue(newValue);
  }, []);

  const handleRunAnalysis = useCallback(() => {
    setShouldFetch(true);
    if (shouldFetch) {
      refetch();
    }
  }, [shouldFetch, refetch]);

  const hasData = data && data.length > 0;

  const getFileName = (path: string): string => {
    const parts = path.split("/");
    return parts[parts.length - 1] || path;
  };

  const getTreemapSeries = (culprit: RepoData) => [
    {
      name: culprit.componentName,
      data: culprit.pathData.map((item) => ({
        x: getFileName(item.path),
        y: item.count,
        meta: {
          fullPath: item.path,
          coverage: item.coverage,
          issueIds: item.issueIds,
          issueLinks: item.issueLinks,
        },
      })),
    },
  ];

  const calculateHeatmapHeight = (itemCount: number): number => {
    const minHeight = 300;
    const maxHeight = 600;
    const heightPerItem = 40;
    return Math.min(maxHeight, Math.max(minHeight, itemCount * heightPerItem));
  };

  return (
    <Card className="card-elevated">
      <CardHeader className="border-border/50 border-b pb-4">
        <CardTitle>{t("components:codeHotspots.title")}</CardTitle>
        <CardDescription>{t("components:codeHotspots.description")}</CardDescription>
      </CardHeader>

      {isError && (
        <CardContent>
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error?.message}</AlertDescription>
          </Alert>
        </CardContent>
      )}

      {data?.length === 0 && !isFetching && (
        <CardContent>
          <Alert>
            <Info className="h-4 w-4" />
            <AlertDescription>
              {t("components:codeHotspots.noHotspotsFor", { workload: workloadValue?.toLocaleUpperCase() })}
            </AlertDescription>
          </Alert>
        </CardContent>
      )}

      <CardContent>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-4 lg:grid-cols-8">
          <div className="col-span-1 md:col-span-2 lg:col-span-2">
            <WorkloadNames
              defaults={workloadValue ? [workloadValue] : []}
              multiSelect={false}
              onChange={handleWorkloadChange}
              disabled={isFetching}
            />
          </div>
          <div className="col-span-1 md:col-span-2 lg:col-span-2">
            <DatePicker
              value={startDate}
              onChange={setStartDate}
              label={t("components:filters.startDate")}
              disabled={isFetching}
            />
          </div>
          <div className="col-span-1 md:col-span-2 lg:col-span-2">
            <Combobox
              value={issueTypes}
              options={issueTypeOptions}
              label={t("components:filters.issueTypes")}
              onChange={(v) => setIssueTypes(Array.isArray(v) ? v : v ? [v] : [])}
              disabled={isFetching || !workloadValue}
              multiple
            />
          </div>
          <div className="col-span-1 md:col-span-2 lg:col-span-2">
            <div className="space-y-1">
              <Label>{t("components:codeHotspots.view")}</Label>
              <ToggleGroup
                type="single"
                value={viewMode}
                onValueChange={(v) => v && setViewMode(v as "table" | "heatmap")}
                className="justify-start"
              >
                <ToggleGroupItem
                  value="heatmap"
                  disabled={!hasData}
                  aria-label={t("components:codeHotspots.heatmapView")}
                >
                  <LayoutGrid className="mr-1 h-4 w-4" />
                  {t("components:codeHotspots.heatmap")}
                </ToggleGroupItem>
                <ToggleGroupItem value="table" disabled={!hasData} aria-label={t("components:codeHotspots.tableView")}>
                  <TableIcon className="mr-1 h-4 w-4" />
                  {t("components:codeHotspots.table")}
                </ToggleGroupItem>
              </ToggleGroup>
            </div>
          </div>
        </div>
      </CardContent>

      <CardContent>
        <Alert>
          <Info className="h-4 w-4" />
          <AlertDescription>{t("components:codeHotspots.analysisInfo")}</AlertDescription>
        </Alert>
      </CardContent>

      <CardFooter>
        <Button variant="default" disabled={!workloadValue || isFetching} onClick={handleRunAnalysis}>
          {isFetching && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          {isFetching ? t("components:codeHotspots.analysing") : t("components:codeHotspots.runAnalysis")}
        </Button>
      </CardFooter>

      {/* Loading skeleton for results */}
      {isFetching && (
        <CardContent className="space-y-4">
          {[1, 2].map((i) => (
            <div key={i} className="space-y-3">
              <Skeleton className="h-6 w-1/4" />
              <div className="space-y-2">
                <Skeleton className="h-10 w-full" />
                <Skeleton className="h-8 w-full" />
                <Skeleton className="h-8 w-full" />
                <Skeleton className="h-8 w-3/4" />
              </div>
            </div>
          ))}
        </CardContent>
      )}

      {hasData && !isFetching && (
        <>
          {/* Understanding the results panel */}
          <CardContent className="pt-0">
            <Accordion type="single" collapsible className="mt-2">
              <AccordionItem value="understanding">
                <AccordionTrigger>
                  <span className="flex items-center gap-2">
                    <Info className="h-4 w-4" />
                    {t("components:codeHotspots.understandingResults")}
                  </span>
                </AccordionTrigger>
                <AccordionContent className="text-sm">
                  <p className="mb-4">
                    <strong>{t("components:codeHotspots.issueRelatedChangesTitle")}</strong>{" "}
                    {t("components:codeHotspots.issueRelatedChangesDescription")}
                  </p>
                  <p className="mb-4">
                    <strong>{t("components:codeHotspots.testCoverageTitle")}</strong>{" "}
                    {t("components:codeHotspots.testCoverageDescription")}
                  </p>
                  <p>
                    <strong>{t("components:codeHotspots.ticketsTitle")}</strong>{" "}
                    {t("components:codeHotspots.ticketsDescription")}
                  </p>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </CardContent>

          <CardContent>
            {data.map((culprit: RepoData, index: number) => (
              <section key={index} className="mb-6">
                <h4 className="mb-2 text-lg font-semibold">
                  {t("components:codeHotspots.analysisOf", { component: culprit.componentName })}
                  <span className="text-muted-foreground ml-2 text-sm">({culprit.repoName})</span>
                </h4>

                {culprit.pathData.length > 0 ? (
                  viewMode === "table" ? (
                    <Table>
                      <TableHeader>
                        <TableRow>
                          {headers.map((header) => (
                            <TableHead key={header.key}>{header.title}</TableHead>
                          ))}
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {culprit.pathData.map((row, rowIndex) => (
                          <TableRow key={rowIndex}>
                            <TableCell className="font-mono text-sm">{row.path}</TableCell>
                            <TableCell>{row.count}</TableCell>
                            <TableCell>
                              {row.issueLinks?.map((link, linkIndex) => (
                                <span key={link.id}>
                                  <a
                                    href={link.url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-primary hover:underline"
                                  >
                                    {link.id}
                                  </a>
                                  {linkIndex < row.issueLinks.length - 1 && ", "}
                                </span>
                              ))}
                            </TableCell>
                            <TableCell>{row.coverage ?? t("components:codeHotspots.notAvailable")}</TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  ) : (
                    <TreemapChart
                      series={getTreemapSeries(culprit)}
                      height={calculateHeatmapHeight(culprit.pathData.length)}
                    />
                  )
                ) : (
                  <p className="text-muted-foreground">{t("components:codeHotspots.noHotspots")}</p>
                )}
              </section>
            ))}
          </CardContent>
        </>
      )}
    </Card>
  );
}

// ui/src/components/CodeHotspots.vue
<template>
  <v-card>
    <v-card-title>Code hotspots</v-card-title>
    <v-card-subtitle>Identify files frequently changed in relation to project issues.</v-card-subtitle>

    <v-card-text v-if="!!isError">
      <v-alert type="error">{{ error?.message }}</v-alert>
    </v-card-text>

    <v-card-text v-if="data?.length === 0">
      <v-alert type="info">No hotspots found for {{ workload?.toLocaleUpperCase() }}</v-alert>
    </v-card-text>

    <v-card-text>
      <v-row>
        <v-col cols="6" md="4" lg="3">
          <workload-names
            :defaults="workload as any"
            :multiSelect="false"
            :includeAllOption="false"
            @input="onWorkloadNamesChanged"
            :operationState="isFetching ? OperationState.Busy : OperationState.Idle"
          />
        </v-col>
        <v-col cols="6" md="4" lg="3">
          <DatePicker
            v-model="startDateValue"
            label="Start date"
            :operation-state="isFetching ? OperationState.Busy : OperationState.Idle"
          />
        </v-col>
        <v-col cols="6" md="4" lg="3">
          <v-select
            v-model="issueTypes"
            :items="availableIssueTypes ?? []"
            label="Issue types"
            hint="Select issue types to filter by. Leave empty to use all configured types."
            multiple
            chips
            clearable
            :disabled="isFetching || !workload"
            :loading="isFetchingIssueTypes"
          />
        </v-col>
        <v-col cols="6" md="4" lg="3">
          <v-btn-toggle v-model="viewMode" mandatory color="primary" variant="outlined">
            <v-btn value="table" :disabled="!hasData">
              <v-icon start>mdi-table</v-icon>
              Table
            </v-btn>
            <v-btn value="heatmap" :disabled="!hasData">
              <v-icon start>mdi-view-grid</v-icon>
              Heatmap
            </v-btn>
          </v-btn-toggle>
        </v-col>
      </v-row>
    </v-card-text>

    <v-card-text>
      <v-alert
        text="This analysis links project management issues to pull requests and quality metrics. Analysis may take some time."
        type="info"
        variant="outlined"
        class="mt-n6"
      ></v-alert>
    </v-card-text>

    <v-card-actions>
      <v-btn
        v-model:pressed="isFetching"
        :disabled="!workload || isFetching"
        variant="elevated"
        color="primary"
        class="ml-2"
        @click="refetch"
      >
        {{ isFetching ? "Analysing..." : "Run analysis" }}
      </v-btn>
    </v-card-actions>

    <v-spacer />

    <v-card-text v-if="hasData" class="pt-0">
      <v-expansion-panels variant="accordion" class="mt-2">
        <v-expansion-panel>
          <v-expansion-panel-title>
            <v-icon start>mdi-information-outline</v-icon>
            Understanding the results
          </v-expansion-panel-title>
          <v-expansion-panel-text>
            <div class="text-body-2">
              <p class="mb-5">
                <strong>Changes:</strong> The number of times a file was modified across all pull requests linked to the
                selected issues. A higher count indicates a file that is frequently touched when resolving issues.
              </p>
              <p class="mb-5">
                <strong>Coverage:</strong> The test coverage percentage for the file from your code analysis tool (e.g.,
                SonarQube). Shows what percentage of the code in that file is covered by tests.
              </p>
              <p class="mb-0">
                <strong>Linked Issues:</strong> The specific issues (tickets) whose associated pull requests modified
                this file. Click on any tile or table row to see the full list.
              </p>
            </div>
          </v-expansion-panel-text>
        </v-expansion-panel>
      </v-expansion-panels>
    </v-card-text>

    <v-card-text>
      <section v-for="(culprit, index) in data" :key="index">
        <h4>
          Analysis of {{ culprit.componentName
          }}<RepoLink :workload-id="culprit.workloadId" :repo-name="culprit.repoName" />
        </h4>

        <!-- Table View -->
        <v-data-table
          v-if="viewMode === 'table' && culprit.pathData.length > 0"
          :headers="headers"
          :items="culprit.pathData"
          :items-per-page="5"
        >
          <template #item.issueIds="{ item }">
            <span v-for="(link, linkIndex) in item.issueLinks" :key="link.id">
              <a :href="link.url" target="_blank" rel="noopener noreferrer">{{ link.id }}</a>
              <span v-if="linkIndex < item.issueLinks.length - 1">, </span>
            </span>
          </template>
        </v-data-table>

        <!-- Heatmap View -->
        <TreemapChart
          v-if="viewMode === 'heatmap' && culprit.pathData.length > 0"
          :series="getTreemapSeries(culprit)"
          :height="calculateHeatmapHeight(culprit.pathData.length)"
        />

        <p class="text--secondary" v-if="culprit.pathData.length === 0">No hotspots.</p>
      </section>
    </v-card-text>
  </v-card>
</template>

<script lang="ts" setup>
import { computed, onMounted, ref, watch } from "vue";
import WorkloadNames from "@/components/inputs/WorkloadNames.vue";
import RepoLink from "@/components/info/RepoLink.vue";
import DatePicker from "@/components/DatePicker.vue";
import TreemapChart from "@/components/charts/TreemapChart.vue";
import { useCodeHotspots, type RepoData } from "@/vue-queries/code-hotspots";
import { useIssueTypes } from "@/vue-queries/issue-types";
import { OperationState } from "@/utils/ui";
import { getOffsetDate } from "@/utils/date";
import { formatISO } from "date-fns";

const props = withDefaults(
  defineProps<{
    executeOnMount: boolean;
    workload?: string;
  }>(),
  {
    executeOnMount: false,
    workload: undefined,
  },
);

const startDateValue = ref<Date>(getOffsetDate(-30));
const startDate = computed(() => formatISO(startDateValue.value, { representation: "date" }));
const workload = ref(props.workload ?? null);
const issueTypes = ref<string[] | undefined>(undefined);
const viewMode = ref<"table" | "heatmap">("heatmap");

// Fetch available issue types when workload changes
const { data: availableIssueTypes, isFetching: isFetchingIssueTypes } = useIssueTypes(workload);

// Reset selected issue types when workload changes
watch(workload, () => {
  issueTypes.value = undefined;
});

const headers = [
  {
    title: "File path",
    key: "path",
  },
  {
    title: "Issue-related changes",
    key: "count",
  },
  {
    title: "Tickets",
    key: "issueIds",
  },
  {
    title: "Test coverage",
    key: "coverage",
  },
];

const { data, error, isError, isFetching, refetch } = useCodeHotspots({
  startDate,
  workload,
  issueTypes,
});

const hasData = computed(() => data.value && data.value.length > 0);

/**
 * Extracts the filename from a full path for display in the heatmap
 */
function getFileName(path: string): string {
  const parts = path.split("/");
  return parts[parts.length - 1] || path;
}

/**
 * Transforms RepoData into series format for the treemap chart
 */
function getTreemapSeries(culprit: RepoData) {
  return [
    {
      name: culprit.componentName,
      data: culprit.pathData.map((item) => ({
        x: getFileName(item.path),
        y: item.count,
        meta: {
          fullPath: item.path,
          coverage: item.coverage,
          issueIds: item.issueIds,
          issueLinks: item.issueLinks,
        },
      })),
    },
  ];
}

/**
 * Calculates an appropriate height for the heatmap based on number of items
 */
function calculateHeatmapHeight(itemCount: number): number {
  const minHeight = 300;
  const maxHeight = 600;
  const heightPerItem = 40;
  return Math.min(maxHeight, Math.max(minHeight, itemCount * heightPerItem));
}

function onWorkloadNamesChanged(rawNewWorkload: string | string[] | null) {
  const newWorkload = rawNewWorkload as string | null;
  workload.value = newWorkload?.length ? newWorkload : null;
}

onMounted(() => {
  if (props.executeOnMount) {
    refetch();
  }
});
</script>
