// frontend/src/components/Predictions.tsx
import { useState, useMemo, useCallback } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { DynamicInputs } from "@/components/inputs";
import { QueryPicker } from "@/components/query";
import { MultiChart, type MultiChartData } from "@/components/charts";
import { Skeleton } from "@/components/ui/skeleton";
import { predict } from "@/services/prediction";
import { convertMetricsObjToMap, getMetricsMetadata } from "@/utils/metrics";
import type { RawQuery } from "@/model/query";
import type { DatedMetrics } from "@/model/metrics";
import { useI18n } from "@/hooks/useI18n";

// Default query selections matching Vue app
const DEFAULT_INPUT_QUERIES = ["code-coverage"];
const DEFAULT_LABEL_QUERY = "bugs-open";

/**
 * Transforms prediction results to MultiChartData format
 */
function createMultiChartDatasets(
  inputs: Map<string, DatedMetrics>[],
  overrides: Record<string, { min: number; max: number }> = {}
): MultiChartData {
  const datasets: { name: string; data: { x: number; y: number }[] }[] = [];

  inputs.forEach((input) => {
    // Group entries by name across all dates
    const groupedByName = new Map<string, { x: number; y: number }[]>();

    input.forEach((datedMetrics, dateStr) => {
      const timestamp = new Date(dateStr).getTime();
      datedMetrics.entries.forEach((entry, name) => {
        if (!groupedByName.has(name)) {
          groupedByName.set(name, []);
        }
        groupedByName.get(name)!.push({
          x: timestamp,
          y: entry.value,
        });
      });
    });

    // Create dataset for each group
    groupedByName.forEach((data, name) => {
      datasets.push({
        name,
        data: data.sort((a, b) => a.x - b.x),
      });
    });
  });

  void overrides; // May be used for axis scaling in future
  return { datasets };
}

export function Predictions() {
  const { t } = useI18n();
  const [inputQueriesModel, setInputQueriesModel] = useState<string[]>(DEFAULT_INPUT_QUERIES);
  const [labelQueryModel, setLabelQueryModel] = useState<string>(DEFAULT_LABEL_QUERY);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [chartData, setChartData] = useState<MultiChartData | null>(null);

  // Compute query types needed for DynamicInputs
  const queryTypes = useMemo(() => {
    const allQueries = [...inputQueriesModel];
    if (labelQueryModel) {
      allQueries.push(labelQueryModel);
    }
    return Array.from(new Set(allQueries));
  }, [inputQueriesModel, labelQueryModel]);

  const handleExecute = useCallback(
    async (queries: RawQuery[]) => {
      if (queries.length === 0) return;

      setIsLoading(true);
      setError(null);
      setChartData(null);

      try {
        // Filter queries into input queries and label query
        const inputQueries = queries.filter((q) => inputQueriesModel.includes(q.queryName));
        const labelQuery = queries.find((q) => q.queryName === labelQueryModel);

        if (!labelQuery) {
          throw new Error("Label query not found");
        }

        // Call the prediction API
        const responseData = await predict(inputQueries, labelQuery);

        // Convert response data to chart format
        const allDatasets: Map<string, DatedMetrics>[] = Object.values(responseData).map((metrics) => {
          return convertMetricsObjToMap(metrics);
        });

        // Get label result for scaling
        const labelResult = convertMetricsObjToMap(responseData[labelQueryModel]);
        const maxLabelResult = getMetricsMetadata(labelResult, (entry) => entry.value).max ?? 0;
        const overrides = { prediction: { min: 0, max: maxLabelResult } };

        // Create chart data
        const newChartData = createMultiChartDatasets(allDatasets, overrides);
        setChartData(newChartData);
      } catch (e) {
        console.error("Failed to run prediction queries", e);
        setError((e as Error).message);
      } finally {
        setIsLoading(false);
      }
    },
    [inputQueriesModel, labelQueryModel]
  );

  return (
    <Card className="card-elevated">
      <CardHeader className="border-border/50 border-b pb-4">
        <div className="flex items-center gap-2">
          <CardTitle>{t("components:predictions.title")}</CardTitle>
          <Badge variant="outline" className="border-blue-500 text-blue-500">
            {t("common:badge.experimental")}
          </Badge>
        </div>
        <CardDescription>{t("components:predictions.description")}</CardDescription>
      </CardHeader>

      <CardContent className="pt-4">
        {/* Query Selection Section */}
        <div className="bg-muted/50 mb-4 space-y-4 rounded-lg p-4">
          <p className="text-muted-foreground text-sm">{t("components:predictions.chooseQueries")}</p>

          <div className="space-y-2">
            <QueryPicker
              value={inputQueriesModel}
              onChange={(v) => setInputQueriesModel(v as string[])}
              multiple
              disabled={isLoading}
              label={t("components:predictions.inputQueries")}
            />
          </div>

          <div className="space-y-2">
            <QueryPicker
              value={labelQueryModel}
              onChange={(v) => setLabelQueryModel(v as string)}
              disabled={isLoading}
              label={t("components:predictions.labelQuery")}
            />
          </div>
        </div>

        {/* Dynamic Inputs */}
        <DynamicInputs queryTypes={queryTypes} queryName="Prediction" isBusy={isLoading} onExecute={handleExecute} />
      </CardContent>

      {/* Loading state */}
      {isLoading && (
        <CardContent className="space-y-4">
          <Skeleton className="h-100 w-full" />
        </CardContent>
      )}

      {/* Error state */}
      {error && (
        <CardContent>
          <div className="text-destructive text-sm">{error}</div>
        </CardContent>
      )}

      {/* Chart */}
      {chartData && chartData.datasets.length > 0 && (
        <CardContent>
          <MultiChart chartData={chartData} height={400} />
        </CardContent>
      )}
    </Card>
  );
}

// ui/src/components/Predictions.vue
<template>
  <v-card>
    <v-card-title>Predict values <v-chip color="blue" outlined small class="ml-2">Experimental</v-chip></v-card-title>
    <v-card-subtitle>Trains a model on two or more datasets, then makes predictions.</v-card-subtitle>

    <v-sheet class="d-flex align-center pa-4" color="accent">
      <v-container fluid>
        <v-row>
          <v-col>
            <div>Choose the queries to train the model.</div>
          </v-col>
        </v-row>
        <v-row no-gutters>
          <v-col>
            <QueryPicker
              label="Input queries"
              multiple
              deletable-chips
              v-model="inputQueriesModel"
              :operationState="operationState"
            />
          </v-col>
        </v-row>
        <v-row no-gutters>
          <v-col>
            <QueryPicker label="Label query" v-model="labelQueryModel" :operationState="operationState" />
          </v-col>
        </v-row>
      </v-container>
    </v-sheet>

    <v-card-text>
      <DynamicInputs
        @execute="onQuery"
        :operation-state="operationState"
        query-name="Prediction"
        :query-types="queryTypes"
      />
    </v-card-text>

    <MultiChart v-if="Object.keys(chartData).length" :chart-data="chartData" />
  </v-card>
</template>

<script lang="ts" setup>
// @ts-nocheck
import { computed, ref } from "vue";
import { uniq } from "lodash";
import DynamicInputs from "@/components/DynamicInputs.vue";
import QueryPicker from "@/components/query/QueryPicker.vue";
import MultiChart from "@/components/charts/MultiChart.vue";
import { convertMetricsObjToMap, getMetricsMetadata } from "@/utils/metrics";
import { predict } from "@/services/prediction";
import { QueryName } from "@/queries/queries";
import { createMultiChartDatasets } from "@/chart/multichart";
import { OperationState } from "@/utils/ui";

const chartData = ref({});
const inputQueriesModel = ref([QueryName.CodeCoverage]);
const labelQueryModel = ref(QueryName.BugsOpen);
const operationState = ref(OperationState.Idle);

async function onQuery(queries) {
  operationState.value = OperationState.Busy;
  try {
    chartData.value = {};

    const inputQueries = queries.filter((q) => inputQueriesModel.value.includes(q.queryName));
    const labelQuery = queries.find((q) => q.queryName === labelQueryModel.value);
    const responseData = await predict(inputQueries, labelQuery);

    const allDatasets = Object.values(responseData).map((metrics) => {
      return convertMetricsObjToMap(metrics);
    });

    const labelResult = convertMetricsObjToMap(responseData[labelQueryModel.value]);
    const maxLabelResult = getMetricsMetadata(labelResult, (entry) => entry.value).max;
    const overrides = { prediction: { min: 0, max: maxLabelResult } };

    chartData.value = createMultiChartDatasets(allDatasets, overrides);
    operationState.value = OperationState.Idle;
  } catch (error) {
    operationState.value = OperationState.Error;
    console.error("Failed to run prediction queries", error);
  }
}

const queryTypes = computed(() => {
  const allQueries = [...inputQueriesModel.value];
  if (labelQueryModel.value) {
    allQueries.push(labelQueryModel.value);
  }
  return uniq(allQueries);
});
</script>
