// frontend/src/components/layout/ThemeSelector.tsx
import { Moon, Sun, Monitor } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useThemeStore, themes } from "@/store/theme";

const themeIcons = {
  light: Sun,
  dark: Moon,
  auto: Monitor,
};

export function ThemeSelector() {
  const { theme, changeTheme } = useThemeStore();
  const CurrentIcon = themeIcons[theme];

  const handleClick = () => {
    const currentIndex = themes.indexOf(theme);
    const newIndex = currentIndex >= themes.length - 1 ? 0 : currentIndex + 1;
    const newTheme = themes[newIndex];
    changeTheme(newTheme);
  };

  return (
    <Button variant="ghost" size="icon" onClick={handleClick}>
      <CurrentIcon className="h-5 w-5" />
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}

// ui/src/components/ThemeSelector.vue
<template>
  <v-btn size="small" @click.prevent="onClickTheme">
    <v-icon>{{ getIcon(themeStore.theme) }}</v-icon>
    <span class="d-sr-only">Toggle theme</span>
  </v-btn>
</template>

<script lang="ts" setup>
import { type Theme, themes, useThemeStore, useThemeWatcher } from "@/store/theme";

useThemeWatcher();

const themeStore = useThemeStore();

function getIcon(theme: Theme) {
  if (theme === "dark") {
    return "mdi-weather-night";
  }
  if (theme === "light") {
    return "mdi-weather-sunny";
  }
  return "mdi-laptop";
}

function onClickTheme() {
  const currentIndex = themes.indexOf(themeStore.theme);
  const newIndex = currentIndex >= themes.length - 1 ? 0 : currentIndex + 1;
  const newTheme = themes[newIndex];
  themeStore.changeTheme(newTheme);
}
</script>
