// ui/src/pages/Analysis.vue
<template>
  <v-sheet color="accent">
    <v-container>
      <v-row>
        <v-col class="pb-8">
          <v-breadcrumbs :items="items"></v-breadcrumbs>
          <h2 class="text-h2">Analysis</h2>
          <p>Combine sources.</p>
        </v-col>
      </v-row>
    </v-container>
  </v-sheet>

  <v-container>
    <v-row>
      <v-col>
        <CodeHotspots
          v-if="!Array.isArray(workloadId)"
          :workload="workloadId as string"
          :executeOnMount="executeImmediately"
        />
        <p v-else>Multiple workloads provided in query, please provide just one.</p>
      </v-col>
    </v-row>

    <v-row>
      <v-col>
        <DynamicQuery
          title="Bugs vs. Coverage"
          subtitle="Correlates bugs vs. coverage."
          :query-types="[QueryName.BugsNew, QueryName.CodeCoverage]"
          :default-inputs="{ workloads: workloadId ? [workloadId] : [] }"
        />
      </v-col>
    </v-row>

    <BehindFlag feature="predictions">
      <v-row>
        <v-col>
          <Predictions />
        </v-col>
      </v-row>
    </BehindFlag>
  </v-container>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import { useRoute } from "vue-router";
import DynamicQuery from "@/components/DynamicQuery.vue";
import Predictions from "@/components/Predictions.vue";
import CodeHotspots from "@/components/CodeHotspots.vue";
import { QueryName } from "@/queries/queries";
import BehindFlag from "@/components/BehindFlag.vue";
import { Paths } from "@/router/paths";

const route = useRoute();

const { workloadId, executeImmediately: executeImmediatelyRaw } = route.query;
const executeImmediately = executeImmediatelyRaw === "true";
const singularWorkloadId = (Array.isArray(workloadId) ? workloadId[0] : workloadId) ?? undefined;

const items = computed(() => [
  {
    title: "Workloads",
    to: Paths.Workloads,
  },
  {
    title: singularWorkloadId ?? "",
    to: `${Paths.Workloads}/${singularWorkloadId ?? ""}`,
  },
  {
    title: "Analysis",
    to: `${Paths.Workloads}/${singularWorkloadId ?? ""}`,
  },
]);
</script>

// frontend/src/pages/Analysis.tsx
import { useSearchParams } from "react-router-dom";
import { PageBreadcrumbs } from "@/components/layout";
import { CodeHotspots } from "@/components/CodeHotspots";
import { DynamicQuery } from "@/components/DynamicQuery";
import { BehindFlag } from "@/components/BehindFlag";
import { Predictions } from "@/components/Predictions";
import { TemporalCoupling } from "@/components/TemporalCoupling";
import { Paths } from "@/router/paths";
import { useI18n } from "@/hooks/useI18n";
import { getWorkloadName } from "@/services/workload";

export default function Analysis() {
  const { t } = useI18n();
  const [searchParams] = useSearchParams();
  const workloadId = searchParams.get("workloadId") ?? undefined;
  const executeImmediately = searchParams.get("executeImmediately") === "true";
  const workloadName = workloadId ? getWorkloadName(workloadId) : undefined;

  const breadcrumbs = workloadId
    ? [
        { label: t("nav:workload"), to: Paths.Workloads },
        { label: workloadName, to: `${Paths.Workloads}/${workloadId}` },
        { label: t("pages:analysis.title") },
      ]
    : [{ label: t("nav:workload"), to: Paths.Workloads }, { label: t("pages:analysis.title") }];

  return (
    <div>
      {/* Header */}
      <section className="header-section py-8">
        <div className="relative z-10 container mx-auto px-4">
          <PageBreadcrumbs items={breadcrumbs} />
          <h2 className="mt-2 text-3xl font-bold">{t("pages:analysis.title")}</h2>
          <p className="text-muted-foreground mt-1">{t("pages:analysis.description")}</p>
        </div>
      </section>

      {/* Content */}
      <div className="container mx-auto space-y-8 px-4 py-8">
        <div>
          <CodeHotspots workload={workloadId} executeOnMount={executeImmediately} />
        </div>

        <BehindFlag feature="temporalCoupling">
          <div>
            <TemporalCoupling workload={workloadId} executeOnMount={executeImmediately} />
          </div>
        </BehindFlag>

        <div>
          <DynamicQuery
            title="Bugs vs. Coverage"
            subtitle="Correlates bugs vs. coverage."
            queryTypes={["bugs-new", "code-coverage"]}
            defaultInputs={workloadId ? { workloads: [workloadId] } : {}}
          />
        </div>

        <BehindFlag feature="predictions">
          <div>
            <Predictions />
          </div>
        </BehindFlag>
      </div>
    </div>
  );
}
