// ui/src/pages/ProgramMetrics.vue
<template>
  <div>
    <v-sheet color="accent">
      <v-container>
        <v-row>
          <v-col class="pb-8">
            <v-breadcrumbs :items="items"></v-breadcrumbs>
            <h2 class="text-h2">Metrics</h2>
          </v-col>
        </v-row>
      </v-container>
    </v-sheet>

    <v-container>
      <v-row>
        <v-col>
          <code-analysis-aggregate />
        </v-col>
      </v-row>

      <v-row>
        <v-col>
          <code-analysis-metric-history />
        </v-col>
      </v-row>

      <v-row>
        <v-col>
          <dynamic-query
            title="Repository churn"
            subtitle="Retrieve historical data for repository churn."
            :query-types="[QueryName.RepoChurn]"
          />
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<script lang="ts" setup>
import { useI18n } from "vue-i18n";
import CodeAnalysisAggregate from "@/components/CodeAnalysisAggregate.vue";
import DynamicQuery from "@/components/DynamicQuery.vue";
import CodeAnalysisMetricHistory from "@/components/CodeAnalysisMetricHistory.vue";
import { QueryName } from "@/queries/queries";
import { Paths } from "@/router/paths";

const { t } = useI18n();

const items = [
  {
    title: t("nav.program"),
    to: Paths.Program,
  },
  {
    title: "Metrics",
    to: Paths.ProgramMetrics,
  },
];
</script>

// frontend/src/pages/ProgramMetrics.tsx
import { PageBreadcrumbs } from "@/components/layout";
import { CodeAnalysisAggregate } from "@/components/CodeAnalysisAggregate";
import { CodeAnalysisMetricHistory } from "@/components/CodeAnalysisMetricHistory";
import { DynamicQuery } from "@/components/DynamicQuery";
import { Paths } from "@/router/paths";
import { getCodeQualityDefaults } from "@/queries/queryDefaults";
import { useI18n } from "@/hooks/useI18n";

export default function ProgramMetrics() {
  const { t } = useI18n();
  const breadcrumbs = [{ label: t("nav:programme"), to: Paths.Program }, { label: t("nav:programmeMetrics") }];

  return (
    <div>
      <div className="header-section">
        <div className="relative z-10 container mx-auto px-4 py-8">
          <PageBreadcrumbs items={breadcrumbs} />
          <h2 className="mt-2 text-4xl font-bold">{t("pages:program.metrics.title")}</h2>
        </div>
      </div>

      <div className="container mx-auto space-y-6 px-4 py-6">
        <div>
          <CodeAnalysisAggregate />
        </div>

        <div>
          <CodeAnalysisMetricHistory />
        </div>

        <div>
          <DynamicQuery
            title={t("pages:program.metrics.repositoryChurnTitle")}
            subtitle={t("pages:program.metrics.repositoryChurnSubtitle")}
            queryTypes={["repo-churn"]}
            defaultInputs={getCodeQualityDefaults()}
          />
        </div>
      </div>
    </div>
  );
}
